REM INSERTING into EXAMS
SET DEFINE OFF;
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (1,1,1,to_date('15-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (2,2,2,to_date('16-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (3,3,3,to_date('17-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (4,4,4,to_date('18-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (5,5,5,to_date('19-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (6,6,6,to_date('20-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (7,7,7,to_date('21-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (8,8,8,to_date('22-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (9,9,9,to_date('23-01-24','DD-MM-RR'),100);
Insert into EXAMS (EXAM_ID,SUBJECT_ID,CLASS_ID,EXAM_DATE,TOTAL_MARKS) values (10,10,10,to_date('24-01-24','DD-MM-RR'),100);
